FROM node:22-alpine

WORKDIR /app

# Copia arquivos de dependência
COPY package*.json ./
COPY tsconfig.json ./

# Instala dependências (incluindo devDependencies para compilar)
RUN npm install

# Copia o código do backend e index.ts
COPY backend ./backend
COPY index.ts ./

# Compila o TypeScript
RUN npm run build

# Expõe a porta do servidor Express
EXPOSE 3001

# Variável de ambiente padrão para se conectar ao container do MongoDB
ENV MONGO_URL=mongodb://mongodb:27017

# Comando para iniciar o servidor Express a partir do código compilado em dist
CMD ["npm", "run", "start"]
